### PR TITLE
Added PATCH Method to response.go

### PR DESCRIPTION
**Pull request by yograterol**
Test run :D

### CODE REVIEW

**Comment by drewolson** [comment]
Thanks for the PR, I'd definitely like to add PATCH functionality. However, I don't want to pull this PR in until the tests run. Please update all the tests to use something other than `pat` that will allow testing PATCH and I'll pull this in.

**Comment by yograterol** [comment]
@drewolson You're right. Well, finding a solution I found that with `add` method of `pat` I can add manually `patch` method.

**Comment by yograterol** [comment]
@drewolson ping

**Comment by drewolson** [comment]
@yograterol I'm sorry, I didn't realize you'd updated this! Looks good, I'll pull it in tonight.

**Pull request merged**
